name: Build GlanceThing Client and attach to release

on:
  workflow_dispatch:

  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Zip the build output
        run: zip -r glancething-client.zip dist/*

      # - name: Upload the zip to the GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: glancething-client.zip
