name: Build Desktop Application and Attach to Release

on:
  workflow_dispatch:
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Wine
        run: sudo apt update && sudo apt install wine64 -y

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build:win

      # - name: Upload the zip to the GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: glancething-*-setup.exe
